// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type GetPaymentInfraByIDInput struct {
	PaymentRackID string `json:"paymentRackId"`
}

type Mutation struct {
}

type PaymentBookingTime struct {
	ID              int             `json:"id"`
	Name            string          `json:"name"`
	UnitMeasurement UnitMeasurement `json:"unitMeasurement"`
	Amount          int             `json:"amount"`
}

type PaymentInfraResponse struct {
	TransactionID string                `json:"transactionId"`
	Message       string                `json:"message"`
	Status        ResponseStatus        `json:"status"`
	PaymentRack   *PaymentRack          `json:"paymentRack,omitempty"`
	Installation  *PaymentInstallation  `json:"installation,omitempty"`
	BookingTimes  []*PaymentBookingTime `json:"bookingTimes"`
}

type PaymentInstallation struct {
	ID       int    `json:"id"`
	Name     string `json:"name"`
	Region   string `json:"region"`
	City     string `json:"city"`
	Address  string `json:"address"`
	ImageURL string `json:"imageUrl"`
}

type PaymentRack struct {
	ID          int    `json:"id"`
	Description string `json:"description"`
	Address     string `json:"address"`
}

type Query struct {
}

type Subscription struct {
}
