// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type AvailableLockersByRackIDAndBookingTimeResponse struct {
	TransactionID   string                   `json:"transactionId"`
	Message         string                   `json:"message"`
	Status          ResponseStatus           `json:"status"`
	TraceID         string                   `json:"traceId"`
	AvailableGroups []*AvailablePaymentGroup `json:"availableGroups"`
}

type AvailablePaymentGroup struct {
	GroupID     int     `json:"groupId"`
	Name        string  `json:"name"`
	Price       float64 `json:"price"`
	Description string  `json:"description"`
	ImageURL    string  `json:"imageUrl"`
}

type BookingStatusData struct {
	ID                     int    `json:"id"`
	ConfigurationBookingID int    `json:"configurationBookingId"`
	InitBooking            string `json:"initBooking"`
	FinishBooking          string `json:"finishBooking"`
	InstallationName       string `json:"installationName"`
	NumberLocker           int    `json:"numberLocker"`
	DeviceID               string `json:"deviceId"`
	CurrentCode            string `json:"currentCode"`
	Openings               int    `json:"openings"`
	ServiceName            string `json:"serviceName"`
	EmailRecipient         string `json:"emailRecipient"`
	CreatedAt              string `json:"createdAt"`
	UpdatedAt              string `json:"updatedAt"`
}

type CheckBookingStatusInput struct {
	ServiceName string `json:"serviceName"`
	CurrentCode string `json:"currentCode"`
}

type CheckBookingStatusResponse struct {
	TransactionID string             `json:"transactionId"`
	Message       string             `json:"message"`
	Status        ResponseStatus     `json:"status"`
	Booking       *BookingStatusData `json:"booking,omitempty"`
}

type ExecuteOpenInput struct {
	ServiceName string `json:"serviceName"`
	CurrentCode string `json:"currentCode"`
}

type ExecuteOpenResponse struct {
	TransactionID string         `json:"transactionId"`
	Message       string         `json:"message"`
	Status        ResponseStatus `json:"status"`
	OpenStatus    OpenStatus     `json:"openStatus"`
}

type GenerateBookingInput struct {
	RackIDReference int     `json:"rackIdReference"`
	GroupID         int     `json:"groupId"`
	CouponCode      *string `json:"couponCode,omitempty"`
	UserEmail       string  `json:"userEmail"`
	UserPhone       string  `json:"userPhone"`
	TraceID         string  `json:"traceId"`
}

type GenerateBookingResponse struct {
	TransactionID string         `json:"transactionId"`
	Message       string         `json:"message"`
	Status        ResponseStatus `json:"status"`
	TraceID       string         `json:"traceId"`
	Code          string         `json:"code"`
}

type GeneratePurchaseOrderInput struct {
	RackIDReference int     `json:"rackIdReference"`
	GroupID         int     `json:"groupId"`
	CouponCode      *string `json:"couponCode,omitempty"`
	UserEmail       string  `json:"userEmail"`
	UserPhone       string  `json:"userPhone"`
	TraceID         string  `json:"traceId"`
	GatewayName     string  `json:"gatewayName"`
}

type GeneratePurchaseOrderResponse struct {
	TransactionID string         `json:"transactionId"`
	Message       string         `json:"message"`
	Status        ResponseStatus `json:"status"`
	TraceID       string         `json:"traceId"`
	URL           string         `json:"url"`
}

type GetAvailableLockersByRackIDAndBookingTimeInput struct {
	PaymentRackID int    `json:"paymentRackId"`
	BookingTimeID int    `json:"bookingTimeId"`
	TraceID       string `json:"traceId"`
}

type GetPaymentInfraByQRValueInput struct {
	QRValue string `json:"qrValue"`
}

type GetPurchaseOrderByPoInput struct {
	PurchaseOrder string `json:"purchaseOrder"`
	TraceID       string `json:"traceId"`
}

type Mutation struct {
}

type PaymentBookingTime struct {
	ID              int             `json:"id"`
	Name            string          `json:"name"`
	UnitMeasurement UnitMeasurement `json:"unitMeasurement"`
	Amount          int             `json:"amount"`
}

type PaymentInfraResponse struct {
	TransactionID string                `json:"transactionId"`
	Message       string                `json:"message"`
	Status        ResponseStatus        `json:"status"`
	TraceID       string                `json:"traceId"`
	PaymentRack   *PaymentRack          `json:"paymentRack,omitempty"`
	Installation  *PaymentInstallation  `json:"installation,omitempty"`
	BookingTimes  []*PaymentBookingTime `json:"bookingTimes"`
}

type PaymentInstallation struct {
	ID       int    `json:"id"`
	Name     string `json:"name"`
	Region   string `json:"region"`
	City     string `json:"city"`
	Address  string `json:"address"`
	ImageURL string `json:"imageUrl"`
}

type PaymentRack struct {
	ID          int    `json:"id"`
	Description string `json:"description"`
	Address     string `json:"address"`
}

type PurchaseOrderData struct {
	CouponID           int    `json:"couponId"`
	BookingReference   int    `json:"bookingReference"`
	Oc                 string `json:"oc"`
	Email              string `json:"email"`
	Phone              string `json:"phone"`
	Discount           int    `json:"discount"`
	ProductPrice       int    `json:"productPrice"`
	FinalProductPrice  string `json:"finalProductPrice"`
	ProductName        string `json:"productName"`
	ProductDescription string `json:"productDescription"`
	LockerPosition     int    `json:"lockerPosition"`
	InstallationName   string `json:"installationName"`
	DeviceSerieNum     string `json:"deviceSerieNum"`
	Status             string `json:"status"`
}

type PurchaseOrderResponse struct {
	TransactionID     string             `json:"transactionId"`
	Message           string             `json:"message"`
	Status            ResponseStatus     `json:"status"`
	TraceID           string             `json:"traceId"`
	PurchaseOrderData *PurchaseOrderData `json:"purchaseOrderData"`
}

type Query struct {
}

type ValidateDiscountCouponInput struct {
	CouponCode string `json:"couponCode"`
	RackID     int    `json:"rackId"`
	TraceID    string `json:"traceId"`
}

type ValidateDiscountCouponResponse struct {
	TransactionID      string         `json:"transactionId"`
	Message            string         `json:"message"`
	Status             ResponseStatus `json:"status"`
	TraceID            string         `json:"traceId"`
	DiscountPercentage float64        `json:"discountPercentage"`
}

type OpenStatus string

const (
	OpenStatusOpenStatusUnspecified OpenStatus = "OPEN_STATUS_UNSPECIFIED"
	OpenStatusOpenStatusReceived    OpenStatus = "OPEN_STATUS_RECEIVED"
	OpenStatusOpenStatusRequested   OpenStatus = "OPEN_STATUS_REQUESTED"
	OpenStatusOpenStatusExecuted    OpenStatus = "OPEN_STATUS_EXECUTED"
	OpenStatusOpenStatusError       OpenStatus = "OPEN_STATUS_ERROR"
	OpenStatusOpenStatusSuccess     OpenStatus = "OPEN_STATUS_SUCCESS"
)

var AllOpenStatus = []OpenStatus{
	OpenStatusOpenStatusUnspecified,
	OpenStatusOpenStatusReceived,
	OpenStatusOpenStatusRequested,
	OpenStatusOpenStatusExecuted,
	OpenStatusOpenStatusError,
	OpenStatusOpenStatusSuccess,
}

func (e OpenStatus) IsValid() bool {
	switch e {
	case OpenStatusOpenStatusUnspecified, OpenStatusOpenStatusReceived, OpenStatusOpenStatusRequested, OpenStatusOpenStatusExecuted, OpenStatusOpenStatusError, OpenStatusOpenStatusSuccess:
		return true
	}
	return false
}

func (e OpenStatus) String() string {
	return string(e)
}

func (e *OpenStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OpenStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OpenStatus", str)
	}
	return nil
}

func (e OpenStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OpenStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OpenStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
