package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"bff-graphql-payment/graph/generated"
	"bff-graphql-payment/graph/model"
	"context"
	"fmt"
)

// GeneratePurchaseOrder is the resolver for the generatePurchaseOrder field.
func (r *mutationResolver) GeneratePurchaseOrder(ctx context.Context, input model.GeneratePurchaseOrderInput) (*model.GeneratePurchaseOrderResponse, error) {
	// Llamar al caso de uso
	order, err := r.paymentInfraService.GeneratePurchaseOrder(ctx, input.RackIDReference, input.GroupID, input.CouponCode, input.UserEmail, input.UserPhone, input.TraceID, input.GatewayName)
	if err != nil {
		return nil, fmt.Errorf("failed to generate purchase order: %w", err)
	}

	// Mapear a respuesta GraphQL
	return r.mapper.ToPurchaseOrderResponse(order), nil
}

// GenerateBooking is the resolver for the generateBooking field.
func (r *mutationResolver) GenerateBooking(ctx context.Context, input model.GenerateBookingInput) (*model.GenerateBookingResponse, error) {
	// Llamar al caso de uso
	booking, err := r.paymentInfraService.GenerateBooking(ctx, input.RackIDReference, input.GroupID, input.CouponCode, input.UserEmail, input.UserPhone, input.TraceID)
	if err != nil {
		return nil, fmt.Errorf("failed to generate booking: %w", err)
	}

	// Mapear a respuesta GraphQL
	return r.mapper.ToBookingResponse(booking), nil
}

// ExecuteOpen is the resolver for the executeOpen field.
func (r *mutationResolver) ExecuteOpen(ctx context.Context, input model.ExecuteOpenInput) (*model.ExecuteOpenResponse, error) {
	// Llamar al caso de uso
	openResult, err := r.paymentInfraService.ExecuteOpen(ctx, input.ServiceName, input.CurrentCode)
	if err != nil {
		return nil, fmt.Errorf("failed to execute open: %w", err)
	}

	// Mapear a respuesta GraphQL
	return r.mapper.ToExecuteOpenResponse(openResult), nil
}

// GetPaymentInfraByQRValue is the resolver for the getPaymentInfraByQrValue field.
func (r *queryResolver) GetPaymentInfraByQRValue(ctx context.Context, input model.GetPaymentInfraByQRValueInput) (*model.PaymentInfraResponse, error) {
	// Llamar al caso de uso
	paymentInfra, err := r.paymentInfraService.GetPaymentInfraByQrValue(ctx, input.QRValue)
	if err != nil {
		return nil, fmt.Errorf("failed to get payment infrastructure: %w", err)
	}

	// Mapear a respuesta GraphQL
	return r.mapper.ToGraphQLResponse(paymentInfra), nil
}

// GetAvailableLockersByRackIDAndBookingTime is the resolver for the getAvailableLockersByRackIDAndBookingTime field.
func (r *queryResolver) GetAvailableLockersByRackIDAndBookingTime(ctx context.Context, input model.GetAvailableLockersByRackIDAndBookingTimeInput) (*model.AvailableLockersByRackIDAndBookingTimeResponse, error) {
	// Llamar al caso de uso
	lockers, err := r.paymentInfraService.GetAvailableLockers(ctx, input.PaymentRackID, input.BookingTimeID, input.TraceID)
	if err != nil {
		return nil, fmt.Errorf("failed to get available lockers: %w", err)
	}

	// Mapear a respuesta GraphQL
	return r.mapper.ToAvailableLockersByRackIDAndBookingTimeResponse(lockers), nil
}

// ValidateDiscountCoupon is the resolver for the validateDiscountCoupon field.
func (r *queryResolver) ValidateDiscountCoupon(ctx context.Context, input model.ValidateDiscountCouponInput) (*model.ValidateDiscountCouponResponse, error) {
	// Llamar al caso de uso
	validation, err := r.paymentInfraService.ValidateDiscountCoupon(ctx, input.CouponCode, input.RackID, input.TraceID)
	if err != nil {
		return nil, fmt.Errorf("failed to validate discount coupon: %w", err)
	}

	// Mapear a respuesta GraphQL
	return r.mapper.ToValidateCouponResponse(validation), nil
}

// GetPurchaseOrderByPo is the resolver for the getPurchaseOrderByPo field.
func (r *queryResolver) GetPurchaseOrderByPo(ctx context.Context, input model.GetPurchaseOrderByPoInput) (*model.PurchaseOrderResponse, error) {
	// Llamar al caso de uso
	orderData, err := r.paymentInfraService.GetPurchaseOrderByPo(ctx, input.PurchaseOrder, input.TraceID)
	if err != nil {
		return nil, fmt.Errorf("failed to get purchase order: %w", err)
	}

	// Mapear a respuesta GraphQL
	return r.mapper.ToPurchaseOrderDataResponse(orderData), nil
}

// CheckBookingStatus is the resolver for the checkBookingStatus field.
func (r *queryResolver) CheckBookingStatus(ctx context.Context, input model.CheckBookingStatusInput) (*model.CheckBookingStatusResponse, error) {
	// Llamar al caso de uso
	bookingStatus, err := r.paymentInfraService.CheckBookingStatus(ctx, input.ServiceName, input.CurrentCode)
	if err != nil {
		return nil, fmt.Errorf("failed to check booking status: %w", err)
	}

	// Mapear a respuesta GraphQL
	return r.mapper.ToBookingStatusResponse(bookingStatus), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
