package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"
	"graphql-payment-bff/graph/generated"
	"graphql-payment-bff/graph/model"
)

// GeneratePurchaseOrder is the resolver for the generatePurchaseOrder field.
func (r *mutationResolver) GeneratePurchaseOrder(ctx context.Context, input model.GeneratePurchaseOrderInput) (*model.GeneratePurchaseOrderResponse, error) {
	// Llamar al caso de uso
	order, err := r.paymentInfraService.GeneratePurchaseOrder(ctx, input.GroupID, input.CouponCode, input.UserEmail, input.UserPhone)
	if err != nil {
		return nil, fmt.Errorf("failed to generate purchase order: %w", err)
	}

	// Mapear a respuesta GraphQL
	return r.mapper.ToPurchaseOrderResponse(order), nil
}

// GetPaymentInfraByQRValue is the resolver for the getPaymentInfraByQrValue field.
func (r *queryResolver) GetPaymentInfraByQRValue(ctx context.Context, input model.GetPaymentInfraByQRValueInput) (*model.PaymentInfraResponse, error) {
	// Llamar al caso de uso
	paymentInfra, err := r.paymentInfraService.GetPaymentInfraByQrValue(ctx, input.QRValue)
	if err != nil {
		return nil, fmt.Errorf("failed to get payment infrastructure: %w", err)
	}

	// Mapear a respuesta GraphQL
	return r.mapper.ToGraphQLResponse(paymentInfra), nil
}

// GetAvailableLockers is the resolver for the getAvailableLockers field.
func (r *queryResolver) GetAvailableLockers(ctx context.Context, input model.GetAvailableLockersInput) (*model.AvailableLockersResponse, error) {
	// Llamar al caso de uso
	lockers, err := r.paymentInfraService.GetAvailableLockers(ctx, input.PaymentRackID, input.BookingTimeID)
	if err != nil {
		return nil, fmt.Errorf("failed to get available lockers: %w", err)
	}

	// Mapear a respuesta GraphQL
	return r.mapper.ToAvailableLockersResponse(lockers), nil
}

// ValidateDiscountCoupon is the resolver for the validateDiscountCoupon field.
func (r *queryResolver) ValidateDiscountCoupon(ctx context.Context, input model.ValidateDiscountCouponInput) (*model.ValidateDiscountCouponResponse, error) {
	// Llamar al caso de uso
	validation, err := r.paymentInfraService.ValidateDiscountCoupon(ctx, input.CouponCode)
	if err != nil {
		return nil, fmt.Errorf("failed to validate discount coupon: %w", err)
	}

	// Mapear a respuesta GraphQL
	return r.mapper.ToValidateCouponResponse(validation), nil
}

// Empty is the resolver for the _empty field.
func (r *subscriptionResolver) Empty(ctx context.Context) (<-chan *string, error) {
	panic(fmt.Errorf("not implemented: Empty - _empty"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
